#!/usr/bin/env python3
"""Converts the 8x8 monochrome PNGs next to this script into ../icons.h.

A pixel is "ink" when it is opaque and dark. Output is one byte per row,
MSB = leftmost pixel -- what Adafruit_GFX::drawBitmap() wants. Rerun whenever
a PNG changes:  python3 icons/gen_icons.py
"""
from pathlib import Path
from PIL import Image

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "icons.h"


def rows(path):
    im = Image.open(path).convert("LA")
    assert im.size == (8, 8), f"{path.name}: expected 8x8, got {im.size}"
    for y in range(8):
        bits = 0
        for x in range(8):
            lum, alpha = im.getpixel((x, y))
            if alpha > 127 and lum < 128:
                bits |= 0x80 >> x
        yield bits


def main():
    lines = [
        "// GENERATED by icons/gen_icons.py from icons/*.png -- do not edit by hand.",
        "// 8x8, 1bpp, one byte per row, MSB = leftmost pixel (Adafruit_GFX drawBitmap).",
        "#pragma once",
        "#include <Arduino.h>",
        "",
        "static const int ICON_SIZE = 8;",
        "",
    ]
    for png in sorted(HERE.glob("*.png")):
        data = list(rows(png))
        body = ", ".join(f"0x{b:02X}" for b in data)
        lines.append(f"static const uint8_t ICON_{png.stem.upper()}[8] PROGMEM = {{ {body} }};")
        for b in data:
            print("".join("#" if b & (0x80 >> x) else "." for x in range(8)), end=" ")
        print(f" <- {png.name}")
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
